In [14]:
# basic imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# imports for splitting into training and testing set

from sklearn.model_selection import train_test_split

# imports for linear, ridge and lasso regression

from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression

In [15]:
# import Boston housing dataset which is an inbuilt dataset of scikit learn

from sklearn.datasets import load_boston
boston=load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [16]:
# dataframe creation

boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['target'] = pd.DataFrame(boston['target'])
boston_df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [17]:
boston_df.mean()
#boston_df.mean(axis=0)
#boston_df.mean(axis=1)

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
target      22.532806
dtype: float64

In [18]:
boston_df.hist(column='CRIM', bins=10)

array([[<AxesSubplot:title={'center':'CRIM'}>]], dtype=object)

In [19]:
# Split the data into X (input) and Y (output)

X = boston_df[boston['feature_names']]
Y = boston_df.target

TrainX = np.asarray(X)
TrainY = np.asarray(Y)

# further splitting X (input) and Y (output) into 80% training data and 20% test data

x_train, x_test, y_train, y_test = train_test_split(TrainX, TrainY, test_size=0.2, random_state=10)

#x_train
#x_test
#y_train
#y_test

In [20]:
# linear regression

linReg = LinearRegression().fit(x_train, y_train)
#linReg.coef_
#linReg.intercept_

linReg.predict(x_test)

array([31.0789639 , 31.721694  , 30.87314928, 22.28234976, 18.85606115,
       16.47132499, 36.05004157, 14.64032337, 25.24078574, 36.92073901,
       21.24395893, 31.05887245, 27.83837442, 33.90940352, 33.94484713,
       40.02040311, 24.14373978, 23.32713796, 25.34120561, 21.49039367,
       32.84083784, 17.72022746, 25.36791791, 24.95097385, 32.39265827,
       20.42497001, 19.33257493, 16.97042135, 38.61885431,  0.99817403,
       32.18145419, 32.02985417, 26.01208772, 23.68917386, 20.38030786,
       19.45806916,  3.46147073, 34.9034939 , 26.98281534, 27.54218642,
       33.89021463, 29.7542196 , 18.15540973, 31.44609872, 17.82446519,
       28.30204573, 19.31527567, 21.90113613, 37.88043957, 16.3464837 ,
       24.68739442, 19.29872222, 24.46627252, 33.91063878, 26.63876989,
       34.33425076, 20.88039511, 19.69421544, 18.70556587, 24.73298651,
       19.89555718, 23.36114411, 39.77392395, 42.09981475, 30.12796703,
       16.7250859 , 23.89207337,  3.48737625, 31.5042913 , 28.36

In [21]:
ridgeReg = Ridge(alpha=0.1).fit(x_train, y_train)
#ridgeReg.coef_
#ridgeReg.intercept_

ridgeReg.predict(x_test)

array([31.06314708, 31.70844546, 30.84209003, 22.37822289, 19.06465212,
       16.52070188, 36.00420966, 14.64996129, 25.17659465, 36.88628624,
       21.21278278, 30.99544423, 27.81640062, 33.88521102, 33.9266118 ,
       40.09624562, 24.23137834, 23.26675304, 25.33774799, 21.69144409,
       32.77394973, 17.80024444, 25.32119691, 24.99589961, 32.38301082,
       20.50963342, 19.28377554, 17.04459305, 38.55991865,  0.83426608,
       32.11396986, 31.98627521, 26.06247955, 23.71970535, 20.32296898,
       19.49800866,  3.50335269, 34.9075389 , 27.00664624, 27.51371778,
       33.9316641 , 29.70752263, 18.17051705, 31.42004129, 17.74504522,
       28.32568048, 19.44641014, 21.85275   , 37.81678605, 16.37445505,
       24.61543697, 19.32015647, 24.42234313, 33.90820765, 26.69739486,
       34.39833562, 20.85332631, 19.84394956, 18.71793342, 24.74633523,
       19.92456137, 23.33315039, 39.71793665, 42.17748336, 30.14654619,
       16.73155008, 23.86453909,  3.47560197, 31.45934217, 28.46

In [22]:
lassoReg = Lasso(alpha=0.1).fit(x_train, y_train)
#lassoReg.coef_
#lassoReg.intercept_

lassoReg.predict(x_test)

array([30.87362989, 31.45824396, 30.54316274, 23.56150215, 22.19249974,
       17.16691686, 35.62722003, 14.98796403, 22.97398963, 36.38327622,
       20.8158988 , 28.68430344, 27.62048436, 33.65699552, 32.1719727 ,
       40.85243237, 25.35259775, 22.77273247, 25.34816995, 22.95240923,
       32.22903689, 18.86621259, 24.82045891, 25.64947568, 32.17713301,
       21.780453  , 18.91008475, 18.05139723, 36.2618938 , -1.15885523,
       31.19211246, 31.47909362, 26.82159518, 24.12998498, 19.5950228 ,
       20.09679439,  3.75139527, 34.89089109, 27.46323529, 27.22715515,
       34.12022227, 29.27743668, 18.34278887, 31.11479353, 16.94249434,
       28.67316669, 21.2496693 , 21.38615832, 36.98250187, 16.92441133,
       24.11865095, 19.57535506, 24.04910173, 33.52328301, 27.57211309,
       35.16321722, 20.58999302, 21.91614947, 19.08146992, 24.80473241,
       20.50376516, 23.01795983, 37.44570141, 42.85166806, 30.32224968,
       16.89892668, 23.60203566,  3.52544443, 31.13288797, 29.45